import Head from 'next/head'
import styles from '../../styles/Sanity.module.css'
import {
  Studio,
} from 'sanity'
import { deskTool } from 'sanity/desk'
import { schemaTypes } from '../../schemas'

export default function Admin() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div id="sanity-studio" className={styles.sanity} />
      <Studio config={{
        name: 'default',
        title: 'nextjs-sanity',
        basePath: '/admin',
        projectId: 'iaou38rg',
        dataset: 'production',

        plugins: [
          deskTool(),
        ],

        schema: {
          types: schemaTypes,
        },
      }} />

    </div>

  )
}

